### ISSUE TITLE
중성과 종성 정보가 바뀜

### ISSUE THREAD

**Issue by kiwiyou** [Danue1/korean-rs#5]
[characters/jungseong.rs](https://github.com/Danue1/korean-rs/blob/master/src/characters/jongseong.rs#L109-L121)에서는 `is_jaeum`과 `is_moeum`이 각각 `false`와 `true`를 반환해야 하는데, 반대로 `true`와 `false`를 반환하고 있습니다. 같은 오류가 [characters/jongseong.rs](https://github.com/Danue1/korean-rs/blob/master/src/characters/jongseong.rs#L109-L121)에서도 나타납니다. 또한 테스트 케이스도 오류를 그대로 반영한 상태입니다.

**Comment by Danue1** [comment]
https://github.com/Danue1/korean-rs/pull/6
